---
- hosts: all
  remote_user: vagrant
  become: true
  vars:
    epics_base_owner: "vagrant"
    epics_base_group: "vagrant"
    epics_base_epics_host_arch: linux-x86_64
    epics_base_base_url: "https://www.aps.anl.gov/epics/download/base/base-7.0.1-rc1.tar.gz"
    epics_base_extensions_top_url: "https://www.aps.anl.gov/epics/download/extensions/extensionsTop_20120904.tar.gz"
    epics_base_base_unarchived_name: "base-7.0.1-rc1"
    epics_base_epics_directory: "/opt/epics/R701"
    epics_base_base_name: "{{ epics_base_epics_directory }}/base"
    epics_base_extensions_name: "{{ epics_base_epics_directory }}/extensions"
    epics_base_modules_name: "{{ epics_base_epics_directory }}/modules"
  roles:
    - role: ansible-role-epics-base
    - role: ansible-role-epics-gateway
    - role: ansible-role-epics-msi
    - role: ansible-role-epics-caSnooper
    - role: ansible-role-epics-autosave
    - role: ansible-role-epics-seq
    - role: ansible-role-epics-asyn
    - role: ansible-role-epics-stream
