---
- hosts: all
  remote_user: vagrant
  vars_files:
    - epics_vars.yml
  roles:
    - role: base
    - role: gateway
    - role: msi
    - role: caSnooper
    - role: seq
    - role: asyn 
    - role: stream
    - role: autosave
