---
- hosts: all
  remote_user: vagrant
  become: true
  vars:
    epics_base_owner: "vagrant"
    epics_base_group: "vagrant"
  roles:
    - role: ansible-role-epics-base
    - role: ansible-role-epics-gateway
    - role: ansible-role-epics-msi
    - role: ansible-role-epics-caSnooper
    - role: ansible-role-epics-autosave
    - role: ansible-role-epics-seq
    - role: ansible-role-epics-asyn
    - role: ansible-role-epics-stream
